version: 1.0.{build}

branches:
  only:
    - linux-build-test

image: Ubuntu1804	

install:
  - sh: nvm install 8.12.0
  - sh: npm i -g https://github.com/frappejs/frappejs-cli
  - yarn

build_script:
  - sh: frappe build electron
  - yarn dist

artifacts:
  - path: build/frappe-accounting_0.0.2_amd64.deb
    name: FrappeAccountingDeb

deploy:
  release: frappe-accounting-v$(APPVEYOR_BUILD_VERSION)
  description: 'Ubuntu release'
  provider: GitHub
  auth_token:
    secure: /+43/Uo02xFON03fqbhjAbp/nqK2orZB0nd8iifboNzyCco01YNRwyKrTZIK9pMv
  artifact: frappe-accounting-0.0.2-x86_64.AppImage
  draft: false
  prerelease: true
  on:
    branch: linux-build-test