version: 1.0.{build}

branches:
  only:
    - windows-build-test

image: Visual Studio 2017

install:
  - ps: Install-Product node 8.12.0 x64
  - npm i -g https://github.com/anto-christo/frappejs-cli#production-build
  - yarn

build_script:
  - ps: frappe build electron
  - ps: npm i -g --production windows-build-tools
  - yarn dist

artifacts:
  - path: build\Frappe-Accounting Setup 0.0.2.exe
    name: FrappeAccountingDeb

deploy:
  release: frappe-accounting-v$(APPVEYOR_BUILD_VERSION)
  description: 'Windows release'
  provider: GitHub
  auth_token:
    secure: rxXh3UopYhGDH+mUpdBF/6K3AaYg0R5SGAt3fApi2rW7p1M6mf7lbL7PzyMajQ4o
  artifact: build\Frappe-Accounting Setup 0.0.2.exe
  draft: false
  prerelease: true
  on:
    branch: windows-build-test